name: "Auto commit and push changes for allowed github actions runner ips"

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:
  

env:
  GITHUB_ACTIONS_RUNNER_ALLOW_IPS_FILE: ./path/to/ips/dir/ips.txt
  
jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Update Ips
        run: |
          mkdir -p $(dirname $GITHUB_ACTIONS_RUNNER_ALLOW_IPS_FILE)
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/meta | jq -r '.actions' | grep -v : | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}\b" | xargs -L1 printf 'allow %s;\n' > $GITHUB_ACTIONS_RUNNER_ALLOW_IPS_FILE
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "cd(actions): autogen ga runner allowed ips (${{ steps.date.outputs.date }})"
          pull_strategy: NO-PULL
          default_author: github_actions
