# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TriggerOnTest

on:
  push:
    branches:
      - "main"
    paths:
      - 'trigger_ci_dir/**.txt'

jobs:
  some-actions:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - run: echo triggered

