# This is a basic workflow to help you get started with Actions

name: WorkFlowOutput

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Workflow Conclusion Action
        # You may pin to the exact commit or the version.
        # uses: technote-space/workflow-conclusion-action@78dd560e96a5b79a07fbc6affc7d6c334ccccf69
        uses: technote-space/workflow-conclusion-action@v2.0.1

      - name: echo result
        run: echo $WORKFLOW_CONCLUSION
