# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PlayGround

on:
  pull_request:
    branches: [ main ]

jobs:
  error-occured:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Collect workflow results
      uses: actions/github-script@v4
      id: set-result
      with:
        script: |
          return JSON.stringify({
            title: "",
            text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`
          })
        result-encoding: string
    - run: echo "${{steps.set-result.outputs.result}}"
