# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PlayGround

on:
  pull_request:
    branches: [ main ]

jobs:
  error-occured:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout this pr (1/3)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout this pr (2/2)
      run: |
        git checkout master
        git checkout -
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: echo something
      run: ecasdho hello
