# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PlayGround

on:
  pull_request:
    branches: [ main ]

jobs:
  some-actions:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout this pr (1/3)
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout this pr (2/2)
      run: |
        git checkout main
        git checkout -
    - uses: actions/github-script@v4
      id: set-template-values
      with:
        script: |
          const pr = "${{ github.repository }}#${{ github.event.number }}"
          const text = `
          **PR**: [${pr}](https://github.com/${pr})
          **actor**: ${{ github.actor }}
          **job status**:
          - lint-and-check:\t${{ needs.lint-and-check.outputs.job-status }}
          - test:\t${{ needs.test.outputs.job-status }}
          `.trim();
          return JSON.stringify({
            title: "${{ github.repository }}",
            text: text,
          });
        result-encoding: string

    - name: Send result to Feishu robot
      uses: xiachufang/actions-feishu@v1.3
      with:
        webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
        message_type: "template"
        msg_template_path: "./.github/feishu_msg_templates/simple.json"
        msg_template_values: "${{steps.set-template-values.outputs.result}}"

        
 #   - name: Setup tmate session
 #     uses: mxschmitt/action-tmate@v3
 #     if: always()
 #     with:
 #       limit-access-to-actor: true
        
