name: "Auto commit and push changes after PR labeled"

on:
  pull_request:
    types:
      - labeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Detect files changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            py_changed:
              - '**.py'
        if: ${{ startsWith(github.event.label.name, 'ci:') }}
        
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        if: ${{ startsWith(github.event.label.name, 'ci:') }} && steps.changes.outputs.py_changed == "true"
        
      - name: Prepare changed py files Deps
        run: |
          pip install black
        if: ${{ startsWith(github.event.label.name, 'ci:') }} && steps.changes.outputs.py_changed == "true"
          
      - name: "With tag ci:black action"
        run: |
          python -m black ${{ steps.changes.outputs.py_changed_files }}
        if: ${{ startsWith(github.event.label.name, 'ci:black') }} && steps.changes.outputs.py_changed == "true"
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "ci(actions): autogen code"
          pull_strategy: NO-PULL
          default_author: github_actions
        if: ${{ startsWith(github.event.label.name, 'ci:') }}
